# NumPy and Python

## Questions
- The differences between a NumPy ndarray and nested lists in Python
- How to construct an ndarray
- NumPy's axis numbering system
- How to access and modify values in an ndarray
- Viewing vs Copying
- NumPy operations - vectorization, broadcasting, and ufuncs

## NumPy vs Python Arrays
> Python can be used to make arrays:

In [1]:
In [1]: matrix = [[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]]
In [2]: [[i + 1 for i in row] for row in matrix]

[[2, 3, 4], [5, 6, 7], [8, 9, 10]]

> But using NumPy, it can be much easier to create larger arrays in different dimensions.
> NumPy arrays are also quicker and more efficient than Python's.
> Ex: Here is a NumPy 1D and 2D array (Each list in the arguments is a row, and each element inside a list is essentially a point):

In [6]:
import numpy as np
array1 = np.array([10, 100, 1000.])
array2 = np.array([[1., 2., 3.],
                   [4., 5., 6.]])

> Note: NumPy's elements must be of all the same datatypes. If you use 'dtype' you can output the datatype.

In [9]:
array2.dtype

dtype('float64')

> With some Python functions, it doesn't allow you to use them on NumPy arrays, but there is a workaround, using NumPy Universal Functions. For example, using Python:

In [ ]:
math.sqrt(array1)

> Using Universal Functions:

In [11]:
np.sqrt(array1)

array([ 3.16227766, 10.        , 31.6227766 ])

> NumPy's arrays have set axes. The rows/the y value are axis 0, and the columns/the x value are axis 1. 
> In addition to the axes, rows and columns are labeled starting at 0, just like the first element in a list of Python.

## Important Functions and Working with Arrays

> 'ones' creates an array of 1s
> 'zeros' creates an array of 0s
> 'eye' creates an identity matrix, which is a matrix where all elements equal 0 except for the ones that equal 1 in a diagonal line from the top left corner to the bottom right corner.
> 'arange' creates an array where the elements are equal to the values in a given range. NumPy's arange is the same as Python's range(). Ex: np.arange(1, 10, 3).
> 'reshaped' allows you to manipulate/move elements in an array with options and arguments to do so.

### Selecting specific elements in an array

> To select a specific element in a NumPy array, the query is array[row, column], in Python, it's array[column][row].

In [12]:
array2[1, 1]

np.float64(5.0)

### Using scalar and arrays

> You can compute math between scalar datatypes and NumPy arrays, when you do this, NumPy will perform the action on each individual element in the array. 
> This is referred to as 'Vectorization'.

In [13]:
array2 * 3

array([[ 3.,  6.,  9.],
       [12., 15., 18.]])

In [14]:
array2 * array1

array([[  10.,  200., 3000.],
       [  40.,  500., 6000.]])